DROP TABLE MOVIES;
DROP TABLE TAGS;
DROP TABLE MOVIE_ACTORS;
DROP TABLE MOVIE_COUNTRIES;
DROP TABLE MOVIE_DIRECTORS;
DROP TABLE MOVIE_GENRES;
DROP TABLE MOVIE_TAGS;
DROP TABLE USER_TAGGEDMOVIES;